# Generated by Django 3.0.6 on 2020-05-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200514_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
